### ISSUE TITLE
I keep getting this error. Any idea what this is about?

### ISSUE THREAD

**Issue by AdarshMJ** [benglard/vidAIo#1]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app
  File "/Users/adarshjamadandi/Desktop/vidAIo-master/app/__init__.py", line 14, in <module>
    from app.api.upload import mod_upload as upload_module
  File "/Users/adarshjamadandi/Desktop/vidAIo-master/app/api/upload.py", line 11, in <module>
    from app.lib.nlp.run_nlp import *
  File "/Users/adarshjamadandi/Desktop/vidAIo-master/app/lib/nlp/run_nlp.py", line 5, in <module>
    from app.lib.nlp.summarizer import *
  File "/Users/adarshjamadandi/Desktop/vidAIo-master/app/lib/nlp/summarizer.py", line 1, in <module>
    from app.lib.nlp.lexrank import LexRank
  File "/Users/adarshjamadandi/Desktop/vidAIo-master/app/lib/nlp/lexrank.py", line 25
    for i in xrange(self.N):
                           ^
SyntaxError: invalid syntax

**Comment by leo-mao** [comment]
Original code lacks a parenthesis.
Or replace your `make_matrix` methods with following code
```
    def make_matrix(self):
        self.matrix = np.zeros((self.N, self.N))
        for i in xrange(self.N):
            for j in xrange(self.N):
                self.matrix[i, j] = self.matrix[j, i] = cos(
                    self.tfidf.matrix[i], self.tfidf.matrix[j]
                )
```

To run the code, make sure you fix all the dependencies at first.
